#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [[ -L "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(readlink "${BASH_SOURCE[0]}")"
    SCRIPT_DIR="$( cd "$( dirname "${SCRIPT_DIR}" )" >/dev/null 2>&1 && pwd )"
fi

# get current package manager, populates 'package_manager'
source ${SCRIPT_DIR}/lib/package-manager.sh

if [[ "$#" -eq 1 && "$1" == "--help" ]]; then
  echo "Usage: pm-list-orphans"
  echo "List all packages that were installed as a dependency but are no longer required."
  exit 0
fi

if [[ ${package_manager} == 'pacman' ]]; then
  pacman --query --deps --unrequired "$@" # -Qdt
elif [[ ${package_manager} == 'brew' ]]; then
  echo "Not implemented, but try 'pm-uninstall-orphans'"
  exit 1
fi
