#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [[ -L "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(readlink "${BASH_SOURCE[0]}")"
    SCRIPT_DIR="$( cd "$( dirname "${SCRIPT_DIR}" )" >/dev/null 2>&1 && pwd )"
fi

# get current package manager, populates 'package_manager'
source ${SCRIPT_DIR}/lib/package-manager.sh

if [[ "$#" -eq 1 && "$1" == "--help" ]]; then
  echo "Usage: pm-list"
  echo "List all installed packages."
  exit 0
fi

if [[ ${package_manager} == 'pacman' ]]; then
  pacman --query | less # -Q
elif [[ ${package_manager} == 'brew' ]]; then
  formulae=$(brew info --json=v2 --installed | jq -r '.formulae[]|.full_name')
  casks=$(brew list -1 --cask)
  { echo "$formulae"; echo "$casks"; } | less
fi
