#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [[ -L "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(readlink "${BASH_SOURCE[0]}")"
    SCRIPT_DIR="$( cd "$( dirname "${SCRIPT_DIR}" )" >/dev/null 2>&1 && pwd )"
fi

# get current package manager, populates 'package_manager'
source ${SCRIPT_DIR}/lib/package-manager.sh

if [[ "$#" -eq 1 && "$1" == "--help" ]]; then
  echo "Usage: pm-uninstall-orphans"
  echo "Uninstall all packages that were installed as a dependency but are no longer required."
  exit 0
fi

if [[ ${package_manager} == 'pacman' ]]; then
  local orphans="$(pm-list-orphans --quiet)"
  if [[ -n "$orphans" ]]; then
    pm-uninstall-package-and-dependencies $(pm-list-orphans --quiet)
  else
    echo "No orphans to uninstall"
  fi
elif [[ ${package_manager} == 'brew' ]]; then
  brew autoremove
fi
